"""
Bets Ledger — persistent record of every tip generated by the pipeline.

Appends new tips on each predict run. Never overwrites existing rows.
Deduplicates on (match_date, home_team, away_team, side, source).

Columns
-------
source        : "live" (real prediction) or "backtest" (walk-forward simulation)
generated_at  : timestamp of the predict/backtest run
match_date    : date the match is played
league        : league name
home_team     :
away_team     :
side          : OVER or UNDER
odds          : odds at time of generation
opening_odds  : first recorded odds from odds_history (before any drift)
odds_drift    : opening_odds - odds (how much the line moved by bet time)
edge_pct      : model edge in % (e.g. 7.5)
signal_tier   : VALUE or SNIPER
drift_signal  : Confirmed / Conflicted / Neutral / New
kelly_pct     : recommended stake as % of bankroll (25% Kelly)
model_type    : standard | new_format
closing_odds  : last recorded odds before kick-off (filled by update_results.py)
clv_pct       : closing line value %
result        : WIN / LOSS / VOID  ← fill manually after the match
pnl           : profit/loss in units ← fill manually (or leave blank for auto)
notes         : anything you want to remember about this bet
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path

import pandas as pd

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config

log = logging.getLogger(__name__)

LEDGER_FILE = config.OUTPUT_DIR / "bets_ledger.csv"

LEDGER_COLS = [
    "source",         # "live" or "backtest"
    "generated_at",
    "match_date",
    "league",
    "home_team",
    "away_team",
    "side",
    "odds",
    "opening_odds",
    "odds_drift",
    "edge_pct",
    "signal_tier",
    "drift_signal",
    "kelly_pct",
    "model_type",     # standard | new_format
    "closing_odds",   # last recorded odds before kick-off (filled by update_results.py)
    "clv_pct",        # closing line value % = (entry_odds - closing_odds) / closing_odds * 100
    "result",
    "pnl",
    "notes",
]


def _kelly_pct(edge: float, odds: float) -> float:
    """25% Kelly stake as % of bankroll."""
    if odds <= 1.0 or edge <= 0.0:
        return 0.0
    full_kelly = edge / (odds - 1.0)
    return round(full_kelly * 0.25 * 100, 2)


def _opening_odds(home: str, away: str, match_date: str, side: str) -> float | str:
    """
    Look up the first recorded odds snapshot for this fixture from odds_history_v9.json.
    Returns the odds value, or "" if not found.
    """
    if not config.ODDS_HISTORY_JSON.exists():
        return ""
    try:
        history = json.loads(config.ODDS_HISTORY_JSON.read_text(encoding="utf-8"))
        key = f"{home} vs {away} | {match_date}"
        snapshots = history.get(key, [])
        if not snapshots:
            return ""
        first = snapshots[0]
        field = "under" if side == "UNDER" else "over"
        val = first.get(field)
        return float(val) if val is not None else ""
    except Exception:
        return ""


def _load_ledger() -> pd.DataFrame:
    """Load ledger, backfilling missing 'source' column on old rows."""
    if LEDGER_FILE.exists():
        df = pd.read_csv(LEDGER_FILE, dtype=str)
        if "source" not in df.columns:
            df.insert(0, "source", "live")
        else:
            df["source"] = df["source"].fillna("live")
        return df
    return pd.DataFrame(columns=LEDGER_COLS)


def _dedup_keys(df: pd.DataFrame) -> set:
    return set(zip(
        df.get("match_date", pd.Series([], dtype=str)).fillna(""),
        df.get("home_team",  pd.Series([], dtype=str)).fillna(""),
        df.get("away_team",  pd.Series([], dtype=str)).fillna(""),
        df.get("side",       pd.Series([], dtype=str)).fillna(""),
        df.get("source",     pd.Series([], dtype=str)).fillna("live"),
    ))


def append_tips(bets_df: pd.DataFrame, source: str = "live") -> None:
    """
    Append new tips into bets_ledger.csv.
    source="live"     → real prediction tips
    source="backtest" → walk-forward simulation bets
    Deduped on (match_date, home, away, side, source).
    """
    if bets_df is None or bets_df.empty:
        return

    existing = _load_ledger()
    # In-place tier upgrades below assign floats/strings into existing cells. CI's pandas can
    # back CSV columns with pyarrow string dtype (future.infer_string), which rejects a float
    # assignment (TypeError). Cast the columns we may overwrite to object so mixed assignment
    # is always safe, regardless of the read dtype backend.
    for _c in ("signal_tier", "edge_pct", "kelly_pct", "drift_signal"):
        if _c in existing.columns:
            existing[_c] = existing[_c].astype(object)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    # Tier ranking for best-tier-wins upgrades. A fixture first appears at a low edge
    # (usually VALUABLE) and may CLIMB to the tier it is actually SENT at. Freezing the
    # first sighting made summaries under-count SNIPER/MARKSMAN (the MARKSMAN=4 bug), so on
    # a re-see we UPGRADE the recorded tier/edge in place to the strongest seen.
    _TIER_RANK = {"SNIPER": 3, "MARKSMAN": 2, "VALUABLE": 1, "": 0, "AVOID": 0, "nan": 0}

    key_to_idx = {}
    for i, r in existing.iterrows():
        k = (str(r["match_date"])[:10], str(r["home_team"]), str(r["away_team"]),
             str(r["side"]).strip(), str(r["source"]))
        key_to_idx[k] = i

    new_rows, upgrades, batch_keys = [], 0, set()

    for _, row in bets_df.iterrows():
        side       = str(row.get("bet", row.get("best_side", ""))).strip()
        match_date = str(row["date"])[:10]
        home       = str(row["home_team"])
        away       = str(row["away_team"])
        dedup_key  = (match_date, home, away, side, source)
        tier       = str(row.get("signal_tier", ""))
        odds       = float(row["odds_under25"] if side == "UNDER" else row["odds_over25"])
        edge       = float(row.get("best_edge", 0.0))

        if dedup_key in key_to_idx:
            # Already logged — UPGRADE tier/edge in place if this run is a stronger tier.
            i   = key_to_idx[dedup_key]
            cur = str(existing.at[i, "signal_tier"])
            if _TIER_RANK.get(tier, 0) > _TIER_RANK.get(cur, 0):
                try:
                    cur_odds = float(existing.at[i, "odds"])
                except (TypeError, ValueError):
                    cur_odds = odds
                existing.at[i, "signal_tier"]  = tier
                existing.at[i, "edge_pct"]     = round(edge * 100, 2)
                existing.at[i, "kelly_pct"]    = _kelly_pct(edge, cur_odds)
                existing.at[i, "drift_signal"] = str(row.get("drift_signal", existing.at[i, "drift_signal"]))
                upgrades += 1
            continue
        if dedup_key in batch_keys:
            continue
        batch_keys.add(dedup_key)

        opening   = _opening_odds(home, away, match_date, side)
        drift_val = round(float(opening) - odds, 3) if isinstance(opening, (int, float)) else ""

        new_rows.append({
            "source":       source,
            "generated_at": now,
            "match_date":   match_date,
            "league":       str(row.get("league", "")),
            "home_team":    home,
            "away_team":    away,
            "side":         side,
            "odds":         odds,
            "opening_odds": opening,
            "odds_drift":   drift_val,
            "edge_pct":     round(edge * 100, 2),
            "signal_tier":  tier,
            "drift_signal": str(row.get("drift_signal", "")),
            "kelly_pct":    _kelly_pct(edge, odds),
            "model_type":   str(row.get("model_type", "")),
            "closing_odds": "",
            "clv_pct":      "",
            "result":       "",
            "pnl":          "",
            "notes":        "",
        })

    if not new_rows and not upgrades:
        log.info("Ledger: no new tips (all already logged).")
        return

    updated = (pd.concat([existing, pd.DataFrame(new_rows, columns=LEDGER_COLS)], ignore_index=True)
               if new_rows else existing)
    updated.to_csv(LEDGER_FILE, index=False)
    log.info(f"Ledger: {len(new_rows)} new + {upgrades} tier-upgrade(s) → {LEDGER_FILE}")


# ── Side-market ledger (BTTS / Over 1.5 / Over 3.5) ─────────────────────────────
SIDE_LEDGER_FILE = config.OUTPUT_DIR / "side_bets_ledger.csv"
SIDE_LEDGER_COLS = [
    "source", "generated_at", "signal_date", "match_date", "league",
    # `side` added 2026-08-22: a stored "btts" row did not say YES or NO, so a settled BTTS tip
    # could not be graded unambiguously from the ledger alone. Every existing row is YES, since the
    # generator has always been one-sided.
    "home_team", "away_team", "market", "side", "odds", "edge_pct", "ev_pct",
    "model_prob", "signal_tier", "model_type", "closing_odds", "clv_pct", "result", "pnl", "notes",
]
_SIDE_RANK = {"SNIPER": 3, "MARKSMAN": 2, "VALUABLE": 1, "": 0, "AVOID": 0, "nan": 0}


def _load_side_ledger() -> pd.DataFrame:
    if SIDE_LEDGER_FILE.exists():
        try:
            return pd.read_csv(SIDE_LEDGER_FILE)
        except Exception:
            pass
    return pd.DataFrame(columns=SIDE_LEDGER_COLS)


def append_side_market_tips(side_df: pd.DataFrame, source: str = "live") -> None:
    """Append BTTS / Over 1.5 / Over 3.5 tips to their OWN ledger (side_bets_ledger.csv),
    one row per (fixture, market), ALL tiers. Same best-tier-wins upgrade as append_tips.

    This is the writer the weekly summary always expected but nothing populated — so side
    markets are now tracked for the season-long live test. result/pnl/closing_odds/clv fill
    in when a settling pass runs; until then rows are 'pending' and readers skip them
    (`_settled_only`), so an unsettled ledger never breaks a summary.
    """
    if side_df is None or side_df.empty:
        return
    existing = _load_side_ledger()
    # Same dtype-safety as append_tips: in-place upgrades assign floats into cells that CI's
    # pandas may back with pyarrow string dtype — cast overwrite targets to object first.
    for _c in ("signal_tier", "edge_pct", "ev_pct", "odds"):
        if _c in existing.columns:
            existing[_c] = existing[_c].astype(object)
    now   = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    today = now[:10]

    key_to_idx = {}
    for i, r in existing.iterrows():
        k = (str(r["match_date"])[:10], str(r["home_team"]), str(r["away_team"]),
             str(r["market"]), str(r["source"]))
        key_to_idx[k] = i

    new_rows, upgrades, batch = [], 0, set()
    for _, row in side_df.iterrows():
        market     = str(row.get("market", ""))
        match_date = str(row["date"])[:10]
        home       = str(row["home_team"])
        away       = str(row["away_team"])
        tier       = str(row.get("signal_tier", ""))
        odds       = float(row.get("market_odds", 0.0) or 0.0)
        edge_pct   = round(float(row.get("edge", 0.0) or 0.0) * 100, 2)
        ev_pct     = round(float(row.get("ev", 0.0) or 0.0) * 100, 2)
        key        = (match_date, home, away, market, source)

        if key in key_to_idx:
            i   = key_to_idx[key]
            cur = str(existing.at[i, "signal_tier"])
            if _SIDE_RANK.get(tier, 0) > _SIDE_RANK.get(cur, 0):
                existing.at[i, "signal_tier"] = tier
                existing.at[i, "edge_pct"]    = edge_pct
                existing.at[i, "ev_pct"]      = ev_pct
                existing.at[i, "odds"]        = odds
                upgrades += 1
            continue
        if key in batch:
            continue
        batch.add(key)

        new_rows.append({
            "source": source, "generated_at": now, "signal_date": today,
            "match_date": match_date, "league": str(row.get("league", "")),
            "home_team": home, "away_team": away, "market": market,
            "odds": odds, "edge_pct": edge_pct, "ev_pct": ev_pct,
            "model_prob": round(float(row.get("model_prob", 0.0) or 0.0), 4),
            "signal_tier": tier,
            "model_type": str(row.get("model_type", "")) or config.model_type_for_league(row.get("league", "")),
            "closing_odds": "", "clv_pct": "", "result": "", "pnl": "", "notes": "",
        })

    if not new_rows and not upgrades:
        log.info("Side ledger: no new tips (all already logged).")
        return
    updated = (pd.concat([existing, pd.DataFrame(new_rows, columns=SIDE_LEDGER_COLS)], ignore_index=True)
               if new_rows else existing)
    updated.to_csv(SIDE_LEDGER_FILE, index=False)
    log.info(f"Side ledger: {len(new_rows)} new + {upgrades} tier-upgrade(s) → {SIDE_LEDGER_FILE}")


# ── HT (half-time O/U) ledger ───────────────────────────────────────────────────
HT_LEDGER_FILE = config.OUTPUT_DIR / "ht_ledger.csv"
HT_LEDGER_COLS = [
    "source", "generated_at", "match_date", "league", "home_team", "away_team",
    "market", "side", "model_prob", "fair_odds",
    # PARITY WITH bets_ledger (added 2026-09-29). HT tips were logged with no PRICE at tip
    # time, so nothing downstream could compute an edge, and settlement fell back to the
    # model's own fair odds on 29 of 38 graded rows — a P/L that restates the model's
    # confidence instead of measuring the market. These four close that gap.
    "odds", "edge_pct", "signal_tier", "model_type",
    "entry_odds", "closing_odds", "clv_pct", "result", "pnl", "notes",
]

#: Informational only. HT is PAPER — these labels let HT be read on the same axis as the other
#: ledgers; they do NOT authorise a stake, and nothing reads them to size one.
def _ht_tier(edge: float | None) -> str:
    if edge is None or pd.isna(edge):
        return "NO_PRICE"
    if edge >= 0.10:
        return "SNIPER"
    if edge >= 0.05:
        return "MARKSMAN"
    if edge >= 0.02:
        return "VALUABLE"
    return "AVOID"


def _ht_price_lookup():
    """Latest captured price per (date, league, home, away, market) for the ht_* markets.

    Returns a callable, or None when no capture file exists. Club names are resolved
    LEAGUE-SCOPED via src.team_names (invariant 11): the ledger carries the predict-side name
    while the capture carries the OddsAPI event name, and they disagree — `Accrington ST`
    against `Accrington Stanley`, `Cheltenham` against `Cheltenham Town`. A bare key match
    finds almost nothing.
    """
    p = config.OUTPUT_DIR / "standard_sidemarket_odds_history.csv"
    if not p.exists():
        return None
    try:
        from src.team_names import resolve
        oh = pd.read_csv(p).sort_values("snapshot_ts")
        oh = oh[oh["market"].astype(str).str.startswith("ht_")]
        if oh.empty:
            return None
        mm = oh["match"].astype(str)
        oh = oh.assign(
            _h=mm.apply(lambda m: m.split(" vs ")[0].strip() if " vs " in m else ""),
            _a=mm.apply(lambda m: m.split(" vs ")[1].strip() if " vs " in m else ""),
            _dk=oh["match_date"].astype(str).str[:10])
        by = {k: g for k, g in oh.groupby(["_dk", "league"], sort=False)}
    except Exception as e:                                            # noqa: BLE001
        log.warning(f"HT ledger: could not read side-market odds ({e})")
        return None

    def _get(day: str, league: str, home: str, away: str, market: str):
        g = by.get((str(day)[:10], str(league)))
        if g is None or g.empty:
            return None
        h = resolve(str(home), list(g["_h"]))
        a = resolve(str(away), list(g["_a"]))
        if not h or not a:
            return None
        m = g[(g["_h"] == h) & (g["_a"] == a) & (g["market"].astype(str) == market)]
        if m.empty:
            return None
        try:
            o = float(m.iloc[-1]["odds"])          # most recent snapshot = price now
            return o if o > 1.0 else None
        except (TypeError, ValueError):
            return None
    return _get


def append_ht_tips(preds_df: pd.DataFrame, source: str = "live") -> None:
    """Log half-time O/U tips (HT model) to ht_ledger.csv — one row per (fixture, HT line).
    Tip thresholds mirror notifier.notify_ht_tips. entry/closing/clv/result fill in when
    update_results settles against captured HT odds (standard_sidemarket_odds_history: the
    ht_* markets) + HT scores. HT is standard-only. Completes open->close->CLV for every model."""
    if preds_df is None or preds_df.empty or "p_ht_over05" not in preds_df.columns:
        return
    existing = pd.read_csv(HT_LEDGER_FILE) if HT_LEDGER_FILE.exists() else pd.DataFrame(columns=HT_LEDGER_COLS)
    seen = {(str(r["match_date"])[:10], str(r["home_team"]), str(r["away_team"]),
             str(r["market"]), str(r["source"])) for _, r in existing.iterrows()} if not existing.empty else set()
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    price = _ht_price_lookup()
    new_rows = []
    for _, row in preds_df.iterrows():
        try:
            p05 = float(row.get("p_ht_over05"))
        except (TypeError, ValueError):
            continue
        if pd.isna(p05):
            continue
        p15 = row.get("p_ht_over15")
        p15 = float(p15) if pd.notna(p15) else None
        if p05 >= 0.75:
            market, side, prob = "ht_over05", "OVER", p05
        elif p05 <= 0.30:
            market, side, prob = "ht_under05", "UNDER", 1 - p05
        elif p15 is not None and p15 >= 0.60:
            market, side, prob = "ht_over15", "OVER", p15
        elif p15 is not None and p15 <= 0.25:
            market, side, prob = "ht_under15", "UNDER", 1 - p15
        else:
            continue
        md = str(row.get("date", ""))[:10]
        home = str(row.get("home_team", "")); away = str(row.get("away_team", ""))
        key = (md, home, away, market, source)
        if key in seen:
            continue
        seen.add(key)
        # PRICE AT TIP TIME. Without it there is no edge and no honest P/L — settlement falls
        # back to the model's own fair odds, which pays exactly what the model implied and so
        # measures nothing about the market.
        lg = str(row.get("league", ""))
        mkt_odds = price(md, lg, home, away, market) if price else None
        edge = (prob - 1.0 / mkt_odds) if mkt_odds else None
        new_rows.append({
            "source": source, "generated_at": now, "match_date": md,
            "league": lg, "home_team": home, "away_team": away,
            "market": market, "side": side, "model_prob": round(prob, 4),
            "fair_odds": round(1.0 / max(prob, 0.01), 2),
            "odds": round(mkt_odds, 3) if mkt_odds else "",
            "edge_pct": round(edge * 100, 2) if edge is not None else "",
            "signal_tier": _ht_tier(edge), "model_type": "ht",
            "entry_odds": round(mkt_odds, 3) if mkt_odds else "",
            "closing_odds": "", "clv_pct": "", "result": "", "pnl": "", "notes": "",
        })
    if not new_rows:
        return
    updated = pd.concat([existing, pd.DataFrame(new_rows, columns=HT_LEDGER_COLS)], ignore_index=True)
    updated.to_csv(HT_LEDGER_FILE, index=False)
    log.info(f"HT ledger: {len(new_rows)} new tip(s) → {HT_LEDGER_FILE}")


def append_backtest_results(backtest_df: pd.DataFrame, model_type: str = "") -> None:
    """
    Append walk-forward backtest bets into the ledger with source="backtest".
    Only OVER/UNDER bets are appended (AVOID rows are skipped).
    """
    bets = backtest_df[backtest_df["bet"].isin(["OVER", "UNDER"])].copy()
    if bets.empty:
        return

    # Map backtest columns → append_tips compatible format
    bets = bets.rename(columns={"bet": "bet", "best_edge": "best_edge"})
    if "best_edge" not in bets.columns and "edge_over" in bets.columns:
        bets["best_edge"] = bets[["edge_over", "edge_under"]].max(axis=1)
    if "model_type" not in bets.columns:
        bets["model_type"] = model_type

    append_tips(bets, source="backtest")


def print_ledger() -> None:
    """Print the full ledger and a SNIPER vs VALUE tier breakdown."""
    if not LEDGER_FILE.exists():
        print("  No ledger yet — run predict first.")
        return

    df = _load_ledger()
    if df.empty:
        print("  Ledger is empty.")
        return

    print(f"\n  {len(df)} total tips logged\n")
    print(df.fillna("").to_string(index=False))

    # Tier × source breakdown (only rows with results)
    scored = df[df["pnl"].notna() & (df["pnl"] != "")].copy()
    if scored.empty:
        return
    scored["pnl"] = pd.to_numeric(scored["pnl"], errors="coerce")

    print("\n" + "=" * 55)
    print("  TIER PERFORMANCE  (resolved bets only)")
    print("=" * 55)
    for src in ["live", "backtest"]:
        grp = scored[scored["source"] == src]
        if grp.empty:
            continue
        print(f"\n  [{src.upper()}]")
        for tier in ["SNIPER", "MARKSMAN", "VALUABLE"]:
            t = grp[grp["signal_tier"] == tier]
            if t.empty:
                continue
            n    = len(t)
            wins = (t["pnl"] > 0).sum()
            pnl  = t["pnl"].sum()
            print(f"    {tier:6s}: {n:4d} bets | WR={wins/n:.1%} | ROI={pnl/n*100:.1f}%")


HT_OBS_FILE = config.OUTPUT_DIR / "ht_observations.csv"
HT_OBS_COLS = [
    "first_seen", "match_date", "league", "home_team", "away_team",
    "p_ht_over05", "p_ht_over15",
    "odds_ht_over05", "odds_ht_under05", "odds_ht_over15", "odds_ht_under15",
    "would_tip", "tip_market",
    "ht_home_goals", "ht_away_goals", "ht_total_goals", "ht_over05", "ht_over15",
]


def append_ht_observations(preds_df: pd.DataFrame) -> None:
    """Log EVERY scored half-time fixture, not only the ones that cross a tip threshold.

    WHY THIS EXISTS. `ht_ledger.csv` records tips, and a tip only happens when the model clears
    0.75 / 0.30 / 0.60 / 0.25. On the upgraded model that fires on 14.1% of fixtures, which
    means roughly 12 priced records a week and about **20 MONTHS** to reach a thousand. Logging
    every scored fixture instead gives ~83 a week and reaches a thousand in about **12 weeks**.

    It is also the better sample, not merely the bigger one. Filtering by the threshold before
    measuring throws away exactly the fixtures that would tell you whether the threshold means
    anything — you can never learn that the model is wrong at p=0.80 by only ever looking at
    p>=0.75. `would_tip` is recorded per row, so the tips-only view is still one filter away,
    while the full distribution stays available for calibration and edge analysis.

    ONE ROW PER FIXTURE, written the first time it is seen. The full open->close price curve
    already lives in standard_sidemarket_odds_history.csv; this captures the model's belief and
    the market price AT THE MOMENT WE SCORED IT, which is the pair an edge is computed from and
    the thing that cannot be reconstructed afterwards.
    """
    if preds_df is None or preds_df.empty or "p_ht_over05" not in preds_df.columns:
        return
    existing = pd.read_csv(HT_OBS_FILE) if HT_OBS_FILE.exists() else pd.DataFrame(columns=HT_OBS_COLS)
    seen = {(str(r["match_date"])[:10], str(r["home_team"]), str(r["away_team"]))
            for _, r in existing.iterrows()} if not existing.empty else set()

    price = _ht_price_lookup()
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    rows = []
    for _, row in preds_df.iterrows():
        try:
            p05 = float(row.get("p_ht_over05"))
        except (TypeError, ValueError):
            continue
        if pd.isna(p05):
            continue
        md = str(row.get("date", ""))[:10]
        home, away = str(row.get("home_team", "")), str(row.get("away_team", ""))
        key = (md, home, away)
        if key in seen:
            continue
        seen.add(key)
        p15 = row.get("p_ht_over15")
        p15 = float(p15) if pd.notna(p15) else None
        lg = str(row.get("league", ""))

        odds = {}
        for mkt in ("ht_over05", "ht_under05", "ht_over15", "ht_under15"):
            o = price(md, lg, home, away, mkt) if price else None
            odds[f"odds_{mkt}"] = round(o, 3) if o else ""

        # Mirror notifier.notify_ht_tips exactly, so `would_tip` means what it says.
        if p05 >= 0.75:
            wt, tm = True, "ht_over05"
        elif p05 <= 0.30:
            wt, tm = True, "ht_under05"
        elif p15 is not None and p15 >= 0.60:
            wt, tm = True, "ht_over15"
        elif p15 is not None and p15 <= 0.25:
            wt, tm = True, "ht_under15"
        else:
            wt, tm = False, ""

        rows.append({"first_seen": now, "match_date": md, "league": lg,
                     "home_team": home, "away_team": away,
                     "p_ht_over05": round(p05, 4),
                     "p_ht_over15": round(p15, 4) if p15 is not None else "",
                     **odds, "would_tip": wt, "tip_market": tm,
                     "ht_home_goals": "", "ht_away_goals": "", "ht_total_goals": "",
                     "ht_over05": "", "ht_over15": ""})
    if not rows:
        return
    out = pd.concat([existing, pd.DataFrame(rows, columns=HT_OBS_COLS)], ignore_index=True)
    HT_OBS_FILE.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(HT_OBS_FILE, index=False)
    log.info(f"HT observations: {len(rows)} new fixture(s) -> {HT_OBS_FILE.name} "
             f"({int(sum(r['would_tip'] for r in rows))} would tip)")
