"""
Bets Ledger — persistent record of every tip generated by the pipeline.

Appends new tips on each predict run. Never overwrites existing rows.
Deduplicates on (match_date, home_team, away_team, side, source).

Columns
-------
source        : "live" (real prediction) or "backtest" (walk-forward simulation)
generated_at  : timestamp of the predict/backtest run
match_date    : date the match is played
league        : league name
home_team     :
away_team     :
side          : OVER or UNDER
odds          : odds at time of generation
opening_odds  : first recorded odds from odds_history (before any drift)
odds_drift    : opening_odds - odds (how much the line moved by bet time)
edge_pct      : model edge in % (e.g. 7.5)
signal_tier   : VALUE or SNIPER
drift_signal  : Confirmed / Conflicted / Neutral / New
kelly_pct     : recommended stake as % of bankroll (25% Kelly)
model_type    : standard | new_format
closing_odds  : last recorded odds before kick-off (filled by update_results.py)
clv_pct       : closing line value %
result        : WIN / LOSS / VOID  ← fill manually after the match
pnl           : profit/loss in units ← fill manually (or leave blank for auto)
notes         : anything you want to remember about this bet
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path

import pandas as pd

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config

log = logging.getLogger(__name__)

LEDGER_FILE = config.OUTPUT_DIR / "bets_ledger.csv"

LEDGER_COLS = [
    "source",         # "live" or "backtest"
    "generated_at",
    "match_date",
    "league",
    "home_team",
    "away_team",
    "side",
    "odds",
    "opening_odds",
    "odds_drift",
    "edge_pct",
    "signal_tier",
    "drift_signal",
    "kelly_pct",
    "model_type",     # standard | new_format
    "closing_odds",   # last recorded odds before kick-off (filled by update_results.py)
    "clv_pct",        # closing line value % = (entry_odds - closing_odds) / closing_odds * 100
    "result",
    "pnl",
    "notes",
]


def _kelly_pct(edge: float, odds: float) -> float:
    """25% Kelly stake as % of bankroll."""
    if odds <= 1.0 or edge <= 0.0:
        return 0.0
    full_kelly = edge / (odds - 1.0)
    return round(full_kelly * 0.25 * 100, 2)


def _opening_odds(home: str, away: str, match_date: str, side: str) -> float | str:
    """
    Look up the first recorded odds snapshot for this fixture from odds_history_v9.json.
    Returns the odds value, or "" if not found.
    """
    if not config.ODDS_HISTORY_JSON.exists():
        return ""
    try:
        history = json.loads(config.ODDS_HISTORY_JSON.read_text(encoding="utf-8"))
        key = f"{home} vs {away} | {match_date}"
        snapshots = history.get(key, [])
        if not snapshots:
            return ""
        first = snapshots[0]
        field = "under" if side == "UNDER" else "over"
        val = first.get(field)
        return float(val) if val is not None else ""
    except Exception:
        return ""


def _load_ledger() -> pd.DataFrame:
    """Load ledger, backfilling missing 'source' column on old rows."""
    if LEDGER_FILE.exists():
        df = pd.read_csv(LEDGER_FILE, dtype=str)
        if "source" not in df.columns:
            df.insert(0, "source", "live")
        else:
            df["source"] = df["source"].fillna("live")
        return df
    return pd.DataFrame(columns=LEDGER_COLS)


def _dedup_keys(df: pd.DataFrame) -> set:
    return set(zip(
        df.get("match_date", pd.Series([], dtype=str)).fillna(""),
        df.get("home_team",  pd.Series([], dtype=str)).fillna(""),
        df.get("away_team",  pd.Series([], dtype=str)).fillna(""),
        df.get("side",       pd.Series([], dtype=str)).fillna(""),
        df.get("source",     pd.Series([], dtype=str)).fillna("live"),
    ))


def append_tips(bets_df: pd.DataFrame, source: str = "live") -> None:
    """
    Append new tips into bets_ledger.csv.
    source="live"     → real prediction tips
    source="backtest" → walk-forward simulation bets
    Deduped on (match_date, home, away, side, source).
    """
    if bets_df is None or bets_df.empty:
        return

    existing = _load_ledger()
    existing_keys = _dedup_keys(existing)
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    new_rows = []

    for _, row in bets_df.iterrows():
        side       = str(row.get("bet", row.get("best_side", ""))).strip()
        match_date = str(row["date"])[:10]
        home       = str(row["home_team"])
        away       = str(row["away_team"])
        dedup_key  = (match_date, home, away, side, source)

        if dedup_key in existing_keys:
            continue

        odds      = float(row["odds_under25"] if side == "UNDER" else row["odds_over25"])
        edge      = float(row.get("best_edge", 0.0))
        opening   = _opening_odds(home, away, match_date, side)
        drift_val = round(float(opening) - odds, 3) if isinstance(opening, (int, float)) else ""

        new_rows.append({
            "source":       source,
            "generated_at": now,
            "match_date":   match_date,
            "league":       str(row.get("league", "")),
            "home_team":    home,
            "away_team":    away,
            "side":         side,
            "odds":         odds,
            "opening_odds": opening,
            "odds_drift":   drift_val,
            "edge_pct":     round(edge * 100, 2),
            "signal_tier":  str(row.get("signal_tier", "")),
            "drift_signal": str(row.get("drift_signal", "")),
            "kelly_pct":    _kelly_pct(edge, odds),
            "model_type":   str(row.get("model_type", "")),
            "closing_odds": "",
            "clv_pct":      "",
            "result":       "",
            "pnl":          "",
            "notes":        "",
        })

    if not new_rows:
        log.info("Ledger: no new tips (all already logged).")
        return

    appended = pd.DataFrame(new_rows, columns=LEDGER_COLS)
    updated  = pd.concat([existing, appended], ignore_index=True)
    updated.to_csv(LEDGER_FILE, index=False)
    log.info(f"Ledger: {len(new_rows)} new tip(s) appended → {LEDGER_FILE}")


def append_backtest_results(backtest_df: pd.DataFrame, model_type: str = "") -> None:
    """
    Append walk-forward backtest bets into the ledger with source="backtest".
    Only OVER/UNDER bets are appended (AVOID rows are skipped).
    """
    bets = backtest_df[backtest_df["bet"].isin(["OVER", "UNDER"])].copy()
    if bets.empty:
        return

    # Map backtest columns → append_tips compatible format
    bets = bets.rename(columns={"bet": "bet", "best_edge": "best_edge"})
    if "best_edge" not in bets.columns and "edge_over" in bets.columns:
        bets["best_edge"] = bets[["edge_over", "edge_under"]].max(axis=1)
    if "model_type" not in bets.columns:
        bets["model_type"] = model_type

    append_tips(bets, source="backtest")


def print_ledger() -> None:
    """Print the full ledger and a SNIPER vs VALUE tier breakdown."""
    if not LEDGER_FILE.exists():
        print("  No ledger yet — run predict first.")
        return

    df = _load_ledger()
    if df.empty:
        print("  Ledger is empty.")
        return

    print(f"\n  {len(df)} total tips logged\n")
    print(df.fillna("").to_string(index=False))

    # Tier × source breakdown (only rows with results)
    scored = df[df["pnl"].notna() & (df["pnl"] != "")].copy()
    if scored.empty:
        return
    scored["pnl"] = pd.to_numeric(scored["pnl"], errors="coerce")

    print("\n" + "=" * 55)
    print("  TIER PERFORMANCE  (resolved bets only)")
    print("=" * 55)
    for src in ["live", "backtest"]:
        grp = scored[scored["source"] == src]
        if grp.empty:
            continue
        print(f"\n  [{src.upper()}]")
        for tier in ["SNIPER", "MARKSMAN", "VALUABLE"]:
            t = grp[grp["signal_tier"] == tier]
            if t.empty:
                continue
            n    = len(t)
            wins = (t["pnl"] > 0).sum()
            pnl  = t["pnl"].sum()
            print(f"    {tier:6s}: {n:4d} bets | WR={wins/n:.1%} | ROI={pnl/n*100:.1f}%")
